---
title: "worksheet7"
author: "Sunny Lee"
date: "3/12/2021"
output: pdf_document
---

1) 
a + b)
```{r}
x1 <- c(3, 2, 4, 1, 2, 4, 4)
x2 <- c(4, 2, 4, 4, 1, 3, 1)

plot(x1, x2, col = c("red", "red", "red", "red", "blue", "blue", "blue"))
abline(-.5, 1)
```

c)
For the maximal margin classifier, we want our shortest distances to be as large as possible. 

d)
```{r}
plot(x1, x2, col = c("red", "red", "red", "red", "blue", "blue", "blue"))
abline(0, 1, lty = 2, lwd = 3)
abline(-.5, 1)
abline(-1, 1, lty = 2, lwd = 3)
```

e) 
The support vectors are indicated in red
```{r}
plot(x1, x2)
abline(0, 1, lty = 2, lwd = 3)
abline(-.5, 1)
abline(-1, 1, lty = 2, lwd = 3)

points(c(2, 2, 4, 4), c(1, 2, 3, 4), col = "green")

```

f) 
No, as the seventh observation is not one of the support vectors, so our function will not change unless the seventh observation gets closer to our margin than the current support vectors. 

g) 
```{r}
plot(x1, x2, col = c("red", "red", "red", "red", "blue", "blue", "blue"))
abline(-1, 1.2)
```

h) 
```{r}
x11 <- c(3, 2, 4, 1, 2, 4, 4, 2)
x21 <- c(4, 2, 4, 4, 1, 3, 1, 3)
plot(x11, x21, col = c("red", "red", "red", "red", "blue", "blue", "blue", "blue"))
```

2
a)
```{r}
set.seed (12)

x=matrix(rnorm(20*2), ncol=2)

y=c(rep(-1,10), rep(1 ,10))

x[y==1,]= x[y==1,] + 1

plot(x, col =(3-y))

 

dat=data.frame(x=x, y=as.factor(y))

library(e1071)

svmfit = svm(y∼., data=dat, kernel = "linear", cost=10, scale=FALSE)

 

plot(svmfit, dat)

 

svmfit$index

summary(svmfit)
```

3)
The coefficients are: 
```{r}
coef(svmfit)
```